[IT-4498] Move s3-redirector.yaml template and fix it
When attempting to deploy the s3-redirector.yaml template AWS throws
the following error..

```
ERROR: Resource WebsiteBucket failed because Resource handler returned message:
"Bucket cannot have ACLs set with ObjectOwnership's BucketOwnerEnforced setting
```

From AWS docs[1]..
```
AccessControl
  This is a legacy property, and it is not recommended for most use cases.
  A majority of modern use cases in Amazon S3 no longer require the use of ACLs,
  and we recommend that you keep ACLs disabled.
```

Therefore we remove `AccessControl` from the template.

[1] https://docs.aws.amazon.com/AWSCloudFormation/latest/TemplateReference/aws-resource-s3-bucket.html#cfn-s3-bucket-accesscontrol